name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements-ci.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install heavy packages
        run: pip install xgboost spacy --timeout 300 --progress-bar off

      - name: Install remaining dependencies
        run: pip install -r requirements-ci.txt --timeout 300 --progress-bar off

      - name: Reset database
        run: rm -f db.sqlite3

      - name: Run migrations
        run: python manage.py migrate

      - name: Run tests
        run: python manage.py test --verbosity=2
